### ISSUE TITLE
请问gitment要怎么装到hexo博客上？

### ISSUE THREAD

**Issue by Holton1** [imsun/gitment#14]
我用github基于hexo建立一个博客，用的Next主题。我想用gitment作为我的评论系统，我照着文档做，但是我不知道要怎么把gitment引入，我的html是hexo自动生成的，我不知道应该把那段代码放在哪里。能不能请你给我一些帮助和提示？谢谢~

**Comment by GeekaholicLin** [comment]
@Holton1  为了在每个页面添加上代码，你需要在Next主题的文件中添加，这样渲染才会引入到每个页面。一般来说，是`_partial/header`文件，我记得Next主题有集成了呀。如果你找不到，可以全局搜索`<head>`标签的位置，然后添加`<script>`标签在`<head>`标签里面，至于` gitment.render(document.getElementById("comments"));`添加到你的评论框之后，用`<script>`标签包围着，给个我主题的示例：
``` ejs
<% if(theme.duoshuo_shortname && theme.duoshuo_shortname.length > 0){ %>
<%- partial('_thirdParty/duoshuo') %>
<% } else{ %>
<% if(theme.disqus_shortname && theme.disqus_shortname.length > 0){ %>
<%- partial('_thirdParty/disqus') %>
<% } else{ %>
<script>
  gitment.render(document.getElementById("comments"));
</script>
<% } %>
<% } %>
```
使用的是ejs，语言可能不同，但逻辑是一样的

**Comment by ehlxr** [comment]
#12

**Comment by dreampiggy** [comment]
如果使用NeXT主题的话，推动这个PR通过即可，如果需要现在体验，自己cherry-pick或者手动改代码到自己的博客主题里面查看效果，测试非常正常，接入很方便，只需要改yml配置。
https://github.com/iissnan/hexo-theme-next/pull/1634

**Comment by iljyya** [comment]
我用的主题还没有封装
```
<script>
var gitment = new Gitment({
  id: '页面 ID', // 可选。默认为 location.href
  owner: 'iljyya',
  repo: 'comments',
  oauth: {
    client_id: 'f851449a81bef86857ac',
    client_secret: '6f3ce61b5e4f9518a13640a35773e5371a575898',
  },
})
gitment.render('container')
</script>
```
请问这段代码我做的对吗？
应该插到 _partial/header 还是 scaffolds/post.md 里呢？

**Comment by iljyya** [comment]
我的 ejs 应该都加对了，但是 hexo s 还是报错 ( 主题是 indigo )
```
INFO  Start processing
ERROR Theme config load failed.
ERROR Process failed: _config.yml
    at generateError (C:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (C:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:168:9) 
.........
```
是主题配置的不对吗？
```
# 开启
gitment:
  owner: 1464125
  repo: comments
  client_id: f851449a81bef86857ac
  client_secret: 6f3ce61b5e4f9518a13640a35773e5371a575898
```

**Comment by SuperBigMouse** [comment]
@iljyya 你的这个问题解决了吗？我也用的indigo，在themes/indigo/_config.yml进行了和你类似的编辑，结果不行

**Comment by iljyya** [comment]
@SuperBigMouse 解决了，我是参数写错了，你也是同样的错误吗，好好检查一下

**Comment by yanzi1225627** [comment]
我是在hexo的next主题5.1.2弄的，刚弄好。欢迎光临[http://yangq.me/post/ab9bb85a.html](http://yangq.me/post/ab9bb85a.html)~

**Comment by Ryanluoxu** [comment]
我的5.1.3 的，Next 预置了Gitment，简单修改即可。详细的可以看：[Hexo-Next 添加 Gitment 评论系统](https://ryanluoxu.github.io/2017/11/27/Hexo-Next-%E6%B7%BB%E5%8A%A0-Gitment-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F/)

**Comment by StevenShiChina** [comment]
@Ryanluoxu  我也用的5.1.3 也照您的设置了，结果还是不显示，求指教
