### ISSUE TITLE
我的 ejs 应该都加对了，但是 hexo s 还是报错

### ISSUE THREAD

**Issue by iljyya** [imsun/gitment#29]
我的 ejs 应该都加对了，但是 hexo s 还是报错  ( 主题是 indigo )
```
INFO  Start processing
ERROR Theme config load failed.
ERROR Process failed: _config.yml
    at generateError (C:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (C:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:168:9) 
.........
```
是主题配置的不对吗？
```
# 开启
gitment:
  owner: 1464125
  repo: comments
  client_id: f851449a81bef86857ac
  client_secret: 6f3ce61b5e4f9518a13640a35773e5371a575898
```

**Comment by imsun** [comment]
你的 owner 不对，应该是 `iljyya` 。可能是我文档写得有歧义。

另外看报错你的 yml 可能有语法错误。
